"""KEEP RAG Service Package.

Exposes abstract contracts, hybrid search pipelines, cross-encoder rerankers,
context builders, citation formatters, vector stores, chunk repositories,
knowledge graph stores, chat history persistence, and RAG synthesis engines.
"""

from backend.app.services.rag.interfaces import (
    AIQueryLogRecord,
    BaseAIQueryLogRepository,
    BaseChatHistoryRepository,
    BaseChunkRepository,
    BaseCitationFormatter,
    BaseContextBuilder,
    BaseHybridSearchService,
    BaseKnowledgeGraphQueryService,
    BaseKnowledgeGraphStore,
    BaseRAGEngine,
    BaseRAGService,
    BaseReranker,
    BaseRetriever,
    BaseVectorStore,
    ChatMessageRecord,
    ChatSessionRecord,
    CitationMetadata,
    ContextBlock,
    DocumentChunkRecord,
    KGEntityRecord,
    KGRelationshipRecord,
    RAGResponse,
    RetrievalResult,
    SearchQuery,
    SearchResultSet,
    StreamEvent,
    StreamEventType,
    VectorFilter,
    VectorRecord,
)

__all__ = [
    "AIQueryLogRecord",
    "BaseAIQueryLogRepository",
    "BaseChatHistoryRepository",
    "BaseChunkRepository",
    "BaseCitationFormatter",
    "BaseContextBuilder",
    "BaseHybridSearchService",
    "BaseKnowledgeGraphQueryService",
    "BaseKnowledgeGraphStore",
    "BaseRAGEngine",
    "BaseRAGService",
    "BaseReranker",
    "BaseRetriever",
    "BaseVectorStore",
    "ChatMessageRecord",
    "ChatSessionRecord",
    "CitationMetadata",
    "ContextBlock",
    "DocumentChunkRecord",
    "KGEntityRecord",
    "KGRelationshipRecord",
    "RAGResponse",
    "RetrievalResult",
    "SearchQuery",
    "SearchResultSet",
    "StreamEvent",
    "StreamEventType",
    "VectorFilter",
    "VectorRecord",
]
